include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
dart_code_metrics:
  rules:
    - avoid-unused-parameters
    - avoid-wrapping-in-padding
    - avoid-returning-widgets
    - avoid-unnecessary-setstate
    - avoid-unused-parameters
    - avoid-nested-conditional-expressions
    - always-remove-listener
    - double-literal-format
    - newline-before-return
    - no-boolean-literal-compare
    - no-equal-then-else
    - no-object-declaration
    - no-empty-block
    - prefer-conditional-expressions
    - prefer-const-border-radius
    - prefer-extracting-callbacks
    - binary-expression-operand-order
    - double-literal-format
    - no-object-declaration

linter:
  rules:
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_types_as_parameter_names
    - avoid_unused_constructor_parameters
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - directives_ordering
    - empty_catches
    - hash_and_equals
    - invariant_booleans
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - non_constant_identifier_names
    - omit_local_variable_types
    - package_api_docs
    - package_prefixed_library_names
    - prefer_final_locals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_single_quotes
    - prefer_typing_uninitialized_variables
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_statements
    - unrelated_type_equality_checks
    - valid_regexps
    - always_put_control_body_on_new_line
    - camel_case_extensions
    - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_final_in_for_each
    - unnecessary_new
    - unnecessary_const
    - use_full_hex_values_for_flutter_colors
    - void_checks
    - file_names
    - empty_statements
    - empty_constructor_bodies
    - curly_braces_in_flow_control_structures
    - avoid_slow_async_io
    - avoid_returning_null_for_void
